// ============================================================
// Internal Links Lookup Table
// Auto-generated from GTP-keywords-to-articles CSV
// 396 URLs across greektriplanner.me
// ============================================================

export interface InternalLink {
  title: string
  url: string
  keywords: string   // space-separated terms for matching
}

export const INTERNAL_LINKS: InternalLink[] = [
  { title: 'AI Greece trip planner', url: 'https://greektriplanner.me/ai-trip-planner', keywords: 'ai greece trip planner' },
  { title: 'How to Plan a Trip to Greece: Complete 2026 Guide', url: 'https://greektriplanner.me/blog/how-to-plan-a-trip-to-greece', keywords: 'how to plan a trip to greece' },
  { title: 'Greece Itinerary 7 Days: Perfect Week-Long Adventure', url: 'https://greektriplanner.me/blog/greece-itinerary-7-days', keywords: 'greece itinerary 7 days' },
  { title: 'Greece Itinerary 10 Days: The Ultimate Journey', url: 'https://greektriplanner.me/blog/greece-itinerary-10-days', keywords: 'greece itinerary 10 days' },
  { title: '3 Days in Athens: Complete Itinerary Guide', url: 'https://greektriplanner.me/blog/3-days-in-athens', keywords: '3 days in athens' },
  { title: '3 Days in Santorini: Perfect Island Itinerary', url: 'https://greektriplanner.me/blog/3-days-in-santorini', keywords: '3 days in santorini' },
  { title: 'Where to Go in Greece for First Time: Complete Guide', url: 'https://greektriplanner.me/blog/where-to-go-in-greece-for-first-time', keywords: 'where to go in greece for first time' },
  { title: 'How Much Does a Greece Trip Cost: Complete Budget Guide', url: 'https://greektriplanner.me/blog/how-much-does-a-trip-to-greece-cost', keywords: 'how much does a greece trip cost' },
  { title: 'Greece Trip for Families Couples & Groups: Complete Planning Guide', url: 'https://greektriplanner.me/blog/greece-trip-families-couples-groups', keywords: 'family trip to greece' },
  { title: 'Italy and Greece Trip: Complete 2026 Planning Guide', url: 'https://greektriplanner.me/blog/italy-and-greece-trip', keywords: 'italy and greece trip' },
  { title: 'Trip to Santorini Greece: Complete 2026 Travel Guide', url: 'https://greektriplanner.me/blog/trip-to-santorini-greece', keywords: 'trip to santorini greece' },
  { title: 'Trip to Athens Greece: Complete 2026 Travel Guide', url: 'https://greektriplanner.me/blog/trip-to-athens-greece', keywords: 'trip to athens greece' },
  { title: 'Trip to Crete Greece: Complete 2026 Travel Guide', url: 'https://greektriplanner.me/blog/trip-to-crete-greece', keywords: 'trip to crete greece' },
  { title: 'Trip to Mykonos Greece: Complete 2026 Travel Guide', url: 'https://greektriplanner.me/blog/trip-to-mykonos-greece', keywords: 'trip to mykonos greece' },
  { title: 'All-Inclusive Trip to Greece: Complete 2026 Guide', url: 'https://greektriplanner.me/blog/all-inclusive-trip-to-greece', keywords: 'all inclusive trip to greece' },
  { title: 'Luxury Trip to Greece: Complete 2026 Guide', url: 'https://greektriplanner.me/blog/luxury-trip-to-greece', keywords: 'luxury trip to greece' },
  { title: 'Solo Trip to Greece: Complete 2026 Guide', url: 'https://greektriplanner.me/blog/solo-trip-to-greece', keywords: 'solo trip to greece' },
  { title: 'Greece Road Trip: Complete 2026 Guide', url: 'https://greektriplanner.me/blog/greece-road-trip', keywords: 'greece road trip' },
  { title: 'Girls Trip to Greece: Complete 2026 Guide', url: 'https://greektriplanner.me/blog/girls-trip-to-greece', keywords: 'girls trip to greece' },
  { title: 'Naxos', url: 'https://greektriplanner.me/blog/naxos-travel-guide', keywords: 'naxos' },
  { title: 'Paros', url: 'https://greektriplanner.me/blog/paros-travel-guide', keywords: 'paros' },
  { title: 'Milos', url: 'https://greektriplanner.me/blog/milos-travel-guide', keywords: 'milos' },
  { title: 'Ios', url: 'https://greektriplanner.me/blog/ios-travel-guide', keywords: 'ios' },
  { title: 'Rhodes', url: 'https://greektriplanner.me/blog/rhodes-travel-guide', keywords: 'rhodes' },
  { title: 'Kos', url: 'https://greektriplanner.me/blog/kos-travel-guide', keywords: 'kos' },
  { title: 'Corfu', url: 'https://greektriplanner.me/blog/corfu-travel-guide', keywords: 'corfu' },
  { title: 'Zakynthos', url: 'https://greektriplanner.me/blog/zakynthos-travel-guide', keywords: 'zakynthos' },
  { title: 'Kefalonia', url: 'https://greektriplanner.me/blog/kefalonia-travel-guide', keywords: 'kefalonia' },
  { title: 'Skopelos', url: 'https://greektriplanner.me/blog/skopelos-travel-guide', keywords: 'skopelos' },
  { title: 'Skiathos', url: 'https://greektriplanner.me/blog/skiathos-travel-guide', keywords: 'skiathos' },
  { title: 'Hydra', url: 'https://greektriplanner.me/blog/hydra-travel-guide', keywords: 'hydra' },
  { title: 'Aegina', url: 'https://greektriplanner.me/blog/aegina-travel-guide', keywords: 'aegina' },
  { title: 'Crete (Overview)', url: 'https://greektriplanner.me/blog/crete-travel-guide', keywords: 'crete (overview)' },
  { title: 'Heraklion', url: 'https://greektriplanner.me/blog/heraklion-travel-guide', keywords: 'heraklion' },
  { title: 'Chania', url: 'https://greektriplanner.me/blog/chania-travel-guide', keywords: 'chania' },
  { title: 'Rethymno', url: 'https://greektriplanner.me/blog/rethymno-travel-guide', keywords: 'rethymno' },
  { title: 'Agios Nikolaos', url: 'https://greektriplanner.me/blog/agios-nikolaos-travel-guide', keywords: 'agios nikolaos' },
  { title: 'Elounda', url: 'https://greektriplanner.me/blog/elounda-travel-guide', keywords: 'elounda' },
  { title: 'Sitia', url: 'https://greektriplanner.me/blog/sitia-travel-guide', keywords: 'sitia' },
  { title: 'Ierapetra', url: 'https://greektriplanner.me/blog/ierapetra-travel-guide', keywords: 'ierapetra' },
  { title: 'Paleochora', url: 'https://greektriplanner.me/blog/paleochora-travel-guide', keywords: 'paleochora' },
  { title: 'Loutro', url: 'https://greektriplanner.me/blog/loutro-travel-guide', keywords: 'loutro' },
  { title: 'Matala', url: 'https://greektriplanner.me/blog/matala-travel-guide', keywords: 'matala' },
  { title: 'Samaria Gorge', url: 'https://greektriplanner.me/blog/samaria-gorge-travel-guide', keywords: 'samaria gorge' },
  { title: 'Balos Beach', url: 'https://greektriplanner.me/blog/balos-beach-travel-guide', keywords: 'balos beach' },
  { title: 'Elafonissi Beach', url: 'https://greektriplanner.me/blog/elafonissi-beach-travel-guide', keywords: 'elafonissi beach' },
  { title: 'Folegandros', url: 'https://greektriplanner.me/blog/folegandros-travel-guide', keywords: 'folegandros' },
  { title: 'Sifnos', url: 'https://greektriplanner.me/blog/sifnos-travel-guide', keywords: 'sifnos' },
  { title: 'Tinos', url: 'https://greektriplanner.me/blog/tinos-travel-guide', keywords: 'tinos' },
  { title: 'Serifos', url: 'https://greektriplanner.me/blog/serifos-travel-guide', keywords: 'serifos' },
  { title: 'Andros', url: 'https://greektriplanner.me/blog/andros-travel-guide', keywords: 'andros' },
  { title: 'Amorgos', url: 'https://greektriplanner.me/blog/amorgos-travel-guide', keywords: 'amorgos' },
  { title: 'Antiparos', url: 'https://greektriplanner.me/blog/antiparos-travel-guide', keywords: 'antiparos' },
  { title: 'Syros', url: 'https://greektriplanner.me/blog/syros-travel-guide', keywords: 'syros' },
  { title: 'Patmos', url: 'https://greektriplanner.me/blog/patmos-travel-guide', keywords: 'patmos' },
  { title: 'Symi', url: 'https://greektriplanner.me/blog/symi-travel-guide', keywords: 'symi' },
  { title: 'Karpathos', url: 'https://greektriplanner.me/blog/karpathos-travel-guide', keywords: 'karpathos' },
  { title: 'Leros', url: 'https://greektriplanner.me/blog/leros-travel-guide', keywords: 'leros' },
  { title: 'Kalymnos', url: 'https://greektriplanner.me/blog/kalymnos-travel-guide', keywords: 'kalymnos' },
  { title: 'Astypalea', url: 'https://greektriplanner.me/blog/astypalea-travel-guide', keywords: 'astypalea' },
  { title: 'Lefkada', url: 'https://greektriplanner.me/blog/lefkada-travel-guide', keywords: 'lefkada' },
  { title: 'Ithaca', url: 'https://greektriplanner.me/blog/ithaca-travel-guide', keywords: 'ithaca' },
  { title: 'Paxos', url: 'https://greektriplanner.me/blog/paxos-travel-guide', keywords: 'paxos' },
  { title: 'Lesbos', url: 'https://greektriplanner.me/blog/lesbos-travel-guide', keywords: 'lesbos' },
  { title: 'Samos', url: 'https://greektriplanner.me/blog/samos-travel-guide', keywords: 'samos' },
  { title: 'Chios', url: 'https://greektriplanner.me/blog/chios-travel-guide', keywords: 'chios' },
  { title: 'Ikaria', url: 'https://greektriplanner.me/blog/ikaria-travel-guide', keywords: 'ikaria' },
  { title: 'Thasos', url: 'https://greektriplanner.me/blog/thasos-travel-guide', keywords: 'thasos' },
  { title: 'Samothrace', url: 'https://greektriplanner.me/blog/samothrace-travel-guide', keywords: 'samothrace' },
  { title: 'Lemnos', url: 'https://greektriplanner.me/blog/lemnos-travel-guide', keywords: 'lemnos' },
  { title: 'Alonissos', url: 'https://greektriplanner.me/blog/alonissos-travel-guide', keywords: 'alonissos' },
  { title: 'Skyros', url: 'https://greektriplanner.me/blog/skyros-travel-guide', keywords: 'skyros' },
  { title: 'Koufonisia', url: 'https://greektriplanner.me/blog/koufonisia-travel-guide', keywords: 'koufonisia' },
  { title: 'Iraklia', url: 'https://greektriplanner.me/blog/iraklia-travel-guide', keywords: 'iraklia' },
  { title: 'Schinoussa', url: 'https://greektriplanner.me/blog/schinoussa-travel-guide', keywords: 'schinoussa' },
  { title: 'Donoussa', url: 'https://greektriplanner.me/blog/donoussa-travel-guide', keywords: 'donoussa' },
  { title: 'Sikinos', url: 'https://greektriplanner.me/blog/sikinos-travel-guide', keywords: 'sikinos' },
  { title: 'Anafi', url: 'https://greektriplanner.me/blog/anafi-travel-guide', keywords: 'anafi' },
  { title: 'Kea', url: 'https://greektriplanner.me/blog/kea-travel-guide', keywords: 'kea' },
  { title: 'Kythnos', url: 'https://greektriplanner.me/blog/kythnos-travel-guide', keywords: 'kythnos' },
  { title: 'Kimolos', url: 'https://greektriplanner.me/blog/kimolos-travel-guide', keywords: 'kimolos' },
  { title: 'Kastellorizo', url: 'https://greektriplanner.me/blog/kastellorizo-travel-guide', keywords: 'kastellorizo' },
  { title: 'Tilos', url: 'https://greektriplanner.me/blog/tilos-travel-guide', keywords: 'tilos' },
  { title: 'Nisyros', url: 'https://greektriplanner.me/blog/nisyros-travel-guide', keywords: 'nisyros' },
  { title: 'Lipsi', url: 'https://greektriplanner.me/blog/lipsi-travel-guide', keywords: 'lipsi' },
  { title: 'Chalki', url: 'https://greektriplanner.me/blog/chalki-travel-guide', keywords: 'chalki' },
  { title: 'Agathonisi', url: 'https://greektriplanner.me/blog/agathonisi-travel-guide', keywords: 'agathonisi' },
  { title: 'Poros', url: 'https://greektriplanner.me/blog/poros-travel-guide', keywords: 'poros' },
  { title: 'Spetses', url: 'https://greektriplanner.me/blog/spetses-travel-guide', keywords: 'spetses' },
  { title: 'Agistri', url: 'https://greektriplanner.me/blog/agistri-travel-guide', keywords: 'agistri' },
  { title: 'Kythira', url: 'https://greektriplanner.me/blog/kythira-travel-guide', keywords: 'kythira' },
  { title: 'Gavdos', url: 'https://greektriplanner.me/blog/gavdos-travel-guide', keywords: 'gavdos' },
  { title: 'Elafonisos', url: 'https://greektriplanner.me/blog/elafonisos-travel-guide', keywords: 'elafonisos' },
  { title: 'Thirassia', url: 'https://greektriplanner.me/blog/thirassia-travel-guide', keywords: 'thirassia' },
  { title: 'Athens', url: 'https://greektriplanner.me/blog/athens-travel-guide', keywords: 'athens' },
  { title: 'Meteora', url: 'https://greektriplanner.me/blog/meteora-travel-guide', keywords: 'meteora' },
  { title: 'Delphi', url: 'https://greektriplanner.me/blog/delphi-travel-guide', keywords: 'delphi' },
  { title: 'Thessaloniki', url: 'https://greektriplanner.me/blog/thessaloniki-travel-guide', keywords: 'thessaloniki' },
  { title: 'Olympia', url: 'https://greektriplanner.me/blog/olympia-travel-guide', keywords: 'olympia' },
  { title: 'Nafplio', url: 'https://greektriplanner.me/blog/nafplio-travel-guide', keywords: 'nafplio' },
  { title: 'Mycenae', url: 'https://greektriplanner.me/blog/mycenae-travel-guide', keywords: 'mycenae' },
  { title: 'Epidaurus', url: 'https://greektriplanner.me/blog/epidaurus-travel-guide', keywords: 'epidaurus' },
  { title: 'Monemvasia', url: 'https://greektriplanner.me/blog/monemvasia-travel-guide', keywords: 'monemvasia' },
  { title: 'Mystras', url: 'https://greektriplanner.me/blog/mystras-travel-guide', keywords: 'mystras' },
  { title: 'Mani Peninsula', url: 'https://greektriplanner.me/blog/mani-peninsula-travel-guide', keywords: 'mani peninsula' },
  { title: 'Kardamyli', url: 'https://greektriplanner.me/blog/kardamyli-travel-guide', keywords: 'kardamyli' },
  { title: 'Sparta', url: 'https://greektriplanner.me/blog/sparta-travel-guide', keywords: 'sparta' },
  { title: 'Ancient Corinth', url: 'https://greektriplanner.me/blog/ancient-corinth-travel-guide', keywords: 'ancient corinth' },
  { title: 'Kalamata', url: 'https://greektriplanner.me/blog/kalamata-travel-guide', keywords: 'kalamata' },
  { title: 'Pylos', url: 'https://greektriplanner.me/blog/pylos-travel-guide', keywords: 'pylos' },
  { title: 'Gytheio', url: 'https://greektriplanner.me/blog/gytheio-travel-guide', keywords: 'gytheio' },
  { title: 'Cape Sounion', url: 'https://greektriplanner.me/blog/cape-sounion-travel-guide', keywords: 'cape sounion' },
  { title: 'Zagori Villages', url: 'https://greektriplanner.me/blog/zagori-villages-travel-guide', keywords: 'zagori villages' },
  { title: 'Vikos Gorge', url: 'https://greektriplanner.me/blog/vikos-gorge-travel-guide', keywords: 'vikos gorge' },
  { title: 'Ioannina', url: 'https://greektriplanner.me/blog/ioannina-travel-guide', keywords: 'ioannina' },
  { title: 'Metsovo', url: 'https://greektriplanner.me/blog/metsovo-travel-guide', keywords: 'metsovo' },
  { title: 'Mount Olympus', url: 'https://greektriplanner.me/blog/mount-olympus-travel-guide', keywords: 'mount olympus' },
  { title: 'Halkidiki', url: 'https://greektriplanner.me/blog/halkidiki-travel-guide', keywords: 'halkidiki' },
  { title: 'Pelion', url: 'https://greektriplanner.me/blog/pelion-travel-guide', keywords: 'pelion' },
  { title: 'Kastoria', url: 'https://greektriplanner.me/blog/kastoria-travel-guide', keywords: 'kastoria' },
  { title: 'Vergina', url: 'https://greektriplanner.me/blog/vergina-travel-guide', keywords: 'vergina' },
  { title: 'Pella', url: 'https://greektriplanner.me/blog/pella-travel-guide', keywords: 'pella' },
  { title: 'Kavala', url: 'https://greektriplanner.me/blog/kavala-travel-guide', keywords: 'kavala' },
  { title: 'Prespa Lakes', url: 'https://greektriplanner.me/blog/prespa-lakes-travel-guide', keywords: 'prespa lakes' },
  { title: 'Lake Kerkini', url: 'https://greektriplanner.me/blog/lake-kerkini-travel-guide', keywords: 'lake kerkini' },
  { title: 'Edessa', url: 'https://greektriplanner.me/blog/edessa-travel-guide', keywords: 'edessa' },
  { title: 'Naousa', url: 'https://greektriplanner.me/blog/naousa-travel-guide', keywords: 'naousa' },
  { title: 'Arachova', url: 'https://greektriplanner.me/blog/arachova-travel-guide', keywords: 'arachova' },
  { title: 'Hosios Loukas', url: 'https://greektriplanner.me/blog/hosios-loukas-travel-guide', keywords: 'hosios loukas' },
  { title: 'Thermopylae', url: 'https://greektriplanner.me/blog/thermopylae-travel-guide', keywords: 'thermopylae' },
  { title: 'Volos', url: 'https://greektriplanner.me/blog/volos-travel-guide', keywords: 'volos' },
  { title: 'Lake Plastira', url: 'https://greektriplanner.me/blog/lake-plastira-travel-guide', keywords: 'lake plastira' },
  { title: 'Kalavryta', url: 'https://greektriplanner.me/blog/kalavryta-travel-guide', keywords: 'kalavryta' },
  { title: 'Galaxidi', url: 'https://greektriplanner.me/blog/galaxidi-travel-guide', keywords: 'galaxidi' },
  { title: 'Parga', url: 'https://greektriplanner.me/blog/parga-travel-guide', keywords: 'parga' },
  { title: 'Preveza', url: 'https://greektriplanner.me/blog/preveza-travel-guide', keywords: 'preveza' },
  { title: 'Syvota', url: 'https://greektriplanner.me/blog/syvota-travel-guide', keywords: 'syvota' },
  { title: 'Dimitsana', url: 'https://greektriplanner.me/blog/dimitsana-travel-guide', keywords: 'dimitsana' },
  { title: 'Stemnitsa', url: 'https://greektriplanner.me/blog/stemnitsa-travel-guide', keywords: 'stemnitsa' },
  { title: 'Methoni', url: 'https://greektriplanner.me/blog/methoni-travel-guide', keywords: 'methoni' },
  { title: 'Koroni', url: 'https://greektriplanner.me/blog/koroni-travel-guide', keywords: 'koroni' },
  { title: 'Vathia', url: 'https://greektriplanner.me/blog/vathia-travel-guide', keywords: 'vathia' },
  { title: 'Limeni', url: 'https://greektriplanner.me/blog/limeni-travel-guide', keywords: 'limeni' },
  { title: 'Areopoli', url: 'https://greektriplanner.me/blog/areopoli-travel-guide', keywords: 'areopoli' },
  { title: 'Ancient Messene', url: 'https://greektriplanner.me/blog/ancient-messene-travel-guide', keywords: 'ancient messene' },
  { title: 'Nemea', url: 'https://greektriplanner.me/blog/nemea-travel-guide', keywords: 'nemea' },
  { title: 'Litochoro', url: 'https://greektriplanner.me/blog/litochoro-travel-guide', keywords: 'litochoro' },
  { title: 'Makrinitsa', url: 'https://greektriplanner.me/blog/makrinitsa-travel-guide', keywords: 'makrinitsa' },
  { title: 'Portaria', url: 'https://greektriplanner.me/blog/portaria-travel-guide', keywords: 'portaria' },
  { title: 'Tsagarada', url: 'https://greektriplanner.me/blog/tsagarada-travel-guide', keywords: 'tsagarada' },
  { title: 'best greek island to visit', url: 'https://greektriplanner.me/blog/best-greek-islands-to-visit', keywords: 'best greek island to visit' },
  { title: 'which greek island has the best beaches', url: 'https://greektriplanner.me/blog/which-greek-island-has-the-best-beaches', keywords: 'which greek island has the best beaches' },
  { title: 'best beaches in greece', url: 'https://greektriplanner.me/blog/best-beaches-in-greece', keywords: 'best beaches in greece' },
  { title: 'best greek islands for couples', url: 'https://greektriplanner.me/blog/best-greek-islands-for-couples', keywords: 'best greek islands for couples' },
  { title: 'best- greek islands for families', url: 'https://greektriplanner.me/blog/best-greek-islands-for-families', keywords: 'best- greek islands for families' },
  { title: 'Best Greek Islands to Visit for the First Time', url: 'https://greektriplanner.me/blog/best-greek-islands-to-visit-for-the-first-time', keywords: 'best greek islands to visit for the first time' },
  { title: 'Best Greek Islands for Beaches', url: 'https://greektriplanner.me/blog/best-greek-islands-for-beaches', keywords: 'best greek islands for beaches' },
  { title: 'Best Places To Visit In Greece', url: 'https://greektriplanner.me/blog/best-places-to-visit-in-greece', keywords: 'best places to visit in greece' },
  { title: 'Best Unknown & Small Greek Islands: 12 Hidden Gems Worth Discovering', url: 'https://greektriplanner.me/blog/best-unknown-and-small-greek-islands', keywords: 'best unknown & small greek islands: 12 hidden gems worth discovering' },
  { title: 'Best Way to See the Greek Islands: Ferries, Sailing & Island-Hopping Explained', url: 'https://greektriplanner.me/blog/best-way-to-see-the-greek-islands', keywords: 'best way to see the greek islands: ferries, sailing & island-hopping explained' },
  { title: 'Best Greek Islands for Nightlife & Young Adults', url: 'https://greektriplanner.me/blog/best-places-to-visit-in-greece-for-young-adults', keywords: 'best greek islands for nightlife & young adults' },
  { title: 'Best Places to Visit in Greece by Month', url: 'https://greektriplanner.me/blog/best-places-to-visit-in-greece-by-month', keywords: 'best places to visit in greece by month' },
  { title: 'Best Greek Islands for History and Beaches', url: 'https://greektriplanner.me/blog/best-greek-islands-for-history-and-beaches', keywords: 'best greek islands for history and beaches' },
  { title: 'Best Greek Islands for Beaches and Food', url: 'https://greektriplanner.me/blog/best-greek-islands-for-beaches-and-food', keywords: 'best greek islands for beaches and food' },
  { title: 'Best Greek Islands for Beaches and Nightlife', url: 'https://greektriplanner.me/blog/best-greek-islands-for-beaches-and-nightlife', keywords: 'best greek islands for beaches and nightlife' },
  { title: 'best-greek-islands-near-athens', url: 'https://greektriplanner.me/blog/best-greek-islands-near-athens', keywords: 'best-greek-islands-near-athens' },
  { title: 'best-historical-places-to-visit-in-greece', url: 'https://greektriplanner.me/blog/best-historical-places-to-visit-in-greece', keywords: 'best-historical-places-to-visit-in-greece' },
  { title: 'best-greek-islands-cruise-guide', url: 'https://greektriplanner.me/blog/best-greek-islands-cruise-guide', keywords: 'best-greek-islands-cruise-guide' },
  { title: 'best-greek-island-tours', url: 'https://greektriplanner.me/blog/best-greek-island-tours', keywords: 'best-greek-island-tours' },
  { title: 'best-hotels-in-the-greek-islands', url: 'https://greektriplanner.me/blog/best-hotels-in-the-greek-islands', keywords: 'best-hotels-in-the-greek-islands' },
  { title: 'greece-vacation-packages', url: 'https://greektriplanner.me/blog/greece-vacation-packages', keywords: 'greece-vacation-packages' },
  { title: 'best-greece-vacation-spots', url: 'https://greektriplanner.me/blog/best-greece-vacation-spots', keywords: 'best-greece-vacation-spots' },
  { title: 'greece-vacation-outfits', url: 'https://greektriplanner.me/blog/greece-vacation-outfits', keywords: 'greece-vacation-outfits' },
  { title: 'crete-overview-travel-guide', url: 'https://greektriplanner.me/blog/crete-overview-travel-guide', keywords: 'crete-overview-travel-guide' },
  { title: 'rhodes-travel-guide', url: 'https://greektriplanner.me/blog/rhodes-travel-guide', keywords: 'rhodes-travel-guide' },
  { title: 'corfu-travel-guide', url: 'https://greektriplanner.me/blog/corfu-travel-guide', keywords: 'corfu-travel-guide' },
  { title: 'best-time-to-travel-to-greece', url: 'https://greektriplanner.me/blog/best-time-to-travel-to-greece', keywords: 'best-time-to-travel-to-greece' },
  { title: 'greece-travel-requirements-for-us-citizens', url: 'https://greektriplanner.me/blog/greece-travel-requirements-for-us-citizens', keywords: 'greece-travel-requirements-for-us-citizens' },
  { title: 'greece-travel-insurance', url: 'https://greektriplanner.me/blog/greece-travel-insurance', keywords: 'greece-travel-insurance' },
  { title: 'is-greece-safe-to-travel-to', url: 'https://greektriplanner.me/blog/is-greece-safe-to-travel-to', keywords: 'is-greece-safe-to-travel-to' },
  { title: 'Greece Tourism Statistics 2025: Record Revenue Amid Shifting Patterns', url: 'https://greektriplanner.me/insights/greece-tourism-statistics-2025', keywords: 'greece tourism statistics 2025' },
  { title: 'visiting-greece-in-winter', url: 'https://greektriplanner.me/blog/visiting-greece-in-winter', keywords: 'visiting-greece-in-winter' },
  { title: 'greece-sailing-vacation', url: 'https://greektriplanner.me/blog/greece-sailing-vacation', keywords: 'greece-sailing-vacation' },
  { title: 'how-to-travel-to-greece-from-the-usa', url: 'https://greektriplanner.me/blog/how-to-travel-to-greece-from-the-usa', keywords: 'how-to-travel-to-greece-from-the-usa' },
  { title: 'best-places-to-visit-in-greece-with-family', url: 'https://greektriplanner.me/blog/best-places-to-visit-in-greece-with-family', keywords: 'best-places-to-visit-in-greece-with-family' },
  { title: 'best-greek-islands-for-solo-travel', url: 'https://greektriplanner.me/blog/best-greek-islands-for-solo-travel', keywords: 'best-greek-islands-for-solo-travel' },
  { title: 'best-places-to-visit-in-greece-for-first-timers', url: 'https://greektriplanner.me/blog/best-places-to-visit-in-greece-for-first-timers', keywords: 'best-places-to-visit-in-greece-for-first-timers' },
  { title: 'greece-tourism-statistics-2020-2025', url: 'https://greektriplanner.me/insights/greece-tourism-statistics-2020-2025', keywords: 'greece-tourism-statistics-2020-2025' },
  { title: 'best-hotels-in-nafplio', url: 'https://greektriplanner.me/blog/best-hotels-in-nafplio', keywords: 'best-hotels-in-nafplio' },
  { title: 'best-restaurants-in-nafplio', url: 'https://greektriplanner.me/blog/best-restaurants-in-nafplio', keywords: 'best-restaurants-in-nafplio' },
  { title: 'olympia-travel-guide', url: 'https://greektriplanner.me/blog/olympia-travel-guide', keywords: 'olympia-travel-guide' },
  { title: 'gytheio-travel-guide', url: 'https://greektriplanner.me/blog/gytheio-travel-guide', keywords: 'gytheio-travel-guide' },
  { title: 'pylos-travel-guide', url: 'https://greektriplanner.me/blog/pylos-travel-guide', keywords: 'pylos-travel-guide' },
  { title: 'ancient-corinth-travel-guide', url: 'https://greektriplanner.me/blog/ancient-corinth-travel-guide', keywords: 'ancient-corinth-travel-guide' },
  { title: 'sparta-travel-guide', url: 'https://greektriplanner.me/blog/sparta-travel-guide', keywords: 'sparta-travel-guide' },
  { title: 'mystras-travel-guide', url: 'https://greektriplanner.me/blog/mystras-travel-guide', keywords: 'mystras-travel-guide' },
  { title: 'monemvasia-travel-guide', url: 'https://greektriplanner.me/blog/monemvasia-travel-guide', keywords: 'monemvasia-travel-guide' },
  { title: 'epidaurus-travel-guide', url: 'https://greektriplanner.me/blog/epidaurus-travel-guide', keywords: 'epidaurus-travel-guide' },
  { title: 'mycenae-travel-guide', url: 'https://greektriplanner.me/blog/mycenae-travel-guide', keywords: 'mycenae-travel-guide' },
  { title: 'best-hotels-in-kalamata', url: 'https://greektriplanner.me/blog/best-hotels-in-kalamata', keywords: 'best-hotels-in-kalamata' },
  { title: 'where-to-stay-in-paros', url: 'https://greektriplanner.me/blog/where-to-stay-in-paros', keywords: 'where-to-stay-in-paros' },
  { title: 'santorini-cruise-caps', url: 'https://greektriplanner.me/insights/santorini-cruise-caps', keywords: 'santorini-cruise-caps' },
  { title: 'santorini-vs-mykonos', url: 'https://greektriplanner.me/blog/santorini-vs-mykonos', keywords: 'santorini-vs-mykonos' },
  { title: 'greece-weather-by-month', url: 'https://greektriplanner.me/blog/greece-weather-by-month', keywords: 'greece-weather-by-month' },
  { title: 'flights-to-greece-from-usa', url: 'https://greektriplanner.me/blog/flights-to-greece-from-usa', keywords: 'flights-to-greece-from-usa' },
  { title: 'mykonos-vs-santorini-vs-crete', url: 'https://greektriplanner.me/blog/mykonos-vs-santorini-vs-crete', keywords: 'mykonos-vs-santorini-vs-crete' },
  { title: 'paros-vs-mykonos', url: 'https://greektriplanner.me/blog/paros-vs-mykonos', keywords: 'paros-vs-mykonos' },
  { title: 'crete-vs-mykonos', url: 'https://greektriplanner.me/blog/crete-vs-mykonos', keywords: 'crete-vs-mykonos' },
  { title: 'corfu-vs-crete', url: 'https://greektriplanner.me/blog/corfu-vs-crete', keywords: 'corfu-vs-crete' },
  { title: 'where-to-stay-in-naxos', url: 'https://greektriplanner.me/blog/where-to-stay-in-naxos', keywords: 'where-to-stay-in-naxos' },
  { title: 'where-to-stay-in-milos', url: 'https://greektriplanner.me/blog/where-to-stay-in-milos', keywords: 'where-to-stay-in-milos' },
  { title: 'greece-cruise-guide-2026', url: 'https://greektriplanner.me/blog/greece-cruise-guide-2026', keywords: 'greece-cruise-guide-2026' },
  { title: 'italy-and-greece-cruise', url: 'https://greektriplanner.me/blog/italy-and-greece-cruise', keywords: 'italy-and-greece-cruise' },
  { title: 'Things to Do in Athens', url: 'https://greektriplanner.me/blog/things-to-do-in-athens', keywords: 'things to do in athens' },
  { title: 'Athens Tours', url: 'https://greektriplanner.me/blog/athens-tours', keywords: 'athens tours' },
  { title: 'Where to Stay in Athens', url: 'https://greektriplanner.me/blog/where-to-stay-in-athens', keywords: 'where to stay in athens' },
  { title: 'Best Hotels in Athens', url: 'https://greektriplanner.me/blog/best-hotels-in-athens', keywords: 'best hotels in athens' },
  { title: 'Best Restaurants in Athens', url: 'https://greektriplanner.me/blog/best-restaurants-in-athens', keywords: 'best restaurants in athens' },
  { title: 'Things to Do in Chania', url: 'https://greektriplanner.me/blog/things-to-do-in-chania', keywords: 'things to do in chania' },
  { title: 'tours-in-chania', url: 'https://greektriplanner.me/blog/tours-in-chania', keywords: 'tours-in-chania' },
  { title: 'Best Hotels in Chania', url: 'https://greektriplanner.me/blog/best-hotels-in-chania', keywords: 'best hotels in chania' },
  { title: 'Best Restaurants in Chania', url: 'https://greektriplanner.me/blog/best-restaurants-in-chania', keywords: 'best restaurants in chania' },
  { title: 'Things to Do in Corfu', url: 'https://greektriplanner.me/blog/things-to-do-in-corfu', keywords: 'things to do in corfu' },
  { title: 'tours-in-corfu', url: 'https://greektriplanner.me/blog/tours-in-corfu', keywords: 'tours-in-corfu' },
  { title: 'Where to Stay in Corfu', url: 'https://greektriplanner.me/blog/where-to-stay-in-corfu', keywords: 'where to stay in corfu' },
  { title: 'Best Hotels in Corfu', url: 'https://greektriplanner.me/blog/best-hotels-in-corfu', keywords: 'best hotels in corfu' },
  { title: 'Best Restaurants in Corfu', url: 'https://greektriplanner.me/blog/best-restaurants-in-corfu', keywords: 'best restaurants in corfu' },
  { title: 'Things to Do in Crete', url: 'https://greektriplanner.me/blog/things-to-do-in-crete', keywords: 'things to do in crete' },
  { title: 'tours-in-crete', url: 'https://greektriplanner.me/blog/tours-in-crete', keywords: 'tours-in-crete' },
  { title: 'Where to Stay in Crete', url: 'https://greektriplanner.me/blog/where-to-stay-in-crete', keywords: 'where to stay in crete' },
  { title: 'Best Hotels in Crete', url: 'https://greektriplanner.me/blog/best-hotels-in-crete', keywords: 'best hotels in crete' },
  { title: 'Best Restaurants in Crete', url: 'https://greektriplanner.me/blog/best-restaurants-in-crete', keywords: 'best restaurants in crete' },
  { title: 'Things to Do in Heraklion', url: 'https://greektriplanner.me/blog/things-to-do-in-heraklion', keywords: 'things to do in heraklion' },
  { title: 'Heraklion Tours', url: 'https://greektriplanner.me/blog/heraklion-tours', keywords: 'heraklion tours' },
  { title: 'Best Hotels in Heraklion', url: 'https://greektriplanner.me/blog/best-hotels-in-heraklion', keywords: 'best hotels in heraklion' },
  { title: 'Best Restaurants in Heraklion', url: 'https://greektriplanner.me/blog/best-restaurants-in-heraklion', keywords: 'best restaurants in heraklion' },
  { title: 'Things to Do in Milos', url: 'https://greektriplanner.me/blog/things-to-do-in-milos', keywords: 'things to do in milos' },
  { title: 'Milos Tours', url: 'https://greektriplanner.me/blog/milos-tours', keywords: 'milos tours' },
  { title: 'Where to Stay in Milos', url: 'https://greektriplanner.me/blog/where-to-stay-in-milos', keywords: 'where to stay in milos' },
  { title: 'Best Hotels in Milos', url: 'https://greektriplanner.me/blog/best-hotels-in-milos', keywords: 'best hotels in milos' },
  { title: 'Best Restaurants in Milos', url: 'https://greektriplanner.me/blog/best-restaurants-in-milos', keywords: 'best restaurants in milos' },
  { title: 'Things to Do in Mykonos', url: 'https://greektriplanner.me/blog/things-to-do-in-mykonos', keywords: 'things to do in mykonos' },
  { title: 'Mykonos Tours', url: 'https://greektriplanner.me/blog/mykonos-tours', keywords: 'mykonos tours' },
  { title: 'Where to Stay in Mykonos', url: 'https://greektriplanner.me/blog/where-to-stay-in-mykonos', keywords: 'where to stay in mykonos' },
  { title: 'Best Hotels in Mykonos', url: 'https://greektriplanner.me/blog/best-hotels-in-mykonos', keywords: 'best hotels in mykonos' },
  { title: 'Best Restaurants in Mykonos', url: 'https://greektriplanner.me/blog/best-restaurants-in-mykonos', keywords: 'best restaurants in mykonos' },
  { title: 'Things to Do in Naxos', url: 'https://greektriplanner.me/blog/things-to-do-in-naxos', keywords: 'things to do in naxos' },
  { title: 'tours-in-naxos', url: 'https://greektriplanner.me/blog/tours-in-naxos', keywords: 'tours-in-naxos' },
  { title: 'Where to Stay in Naxos', url: 'https://greektriplanner.me/blog/where-to-stay-in-naxos', keywords: 'where to stay in naxos' },
  { title: 'Best Hotels in Naxos', url: 'https://greektriplanner.me/blog/best-hotels-in-naxos', keywords: 'best hotels in naxos' },
  { title: 'Best Restaurants in Naxos', url: 'https://greektriplanner.me/blog/best-restaurants-in-naxos', keywords: 'best restaurants in naxos' },
  { title: 'Things to Do in Paros', url: 'https://greektriplanner.me/blog/things-to-do-in-paros', keywords: 'things to do in paros' },
  { title: 'Paros Tours', url: 'https://greektriplanner.me/blog/paros-tours', keywords: 'paros tours' },
  { title: 'Where to Stay in Paros', url: 'https://greektriplanner.me/blog/where-to-stay-in-paros', keywords: 'where to stay in paros' },
  { title: 'Best Hotels in Paros', url: 'https://greektriplanner.me/blog/best-hotels-in-paros', keywords: 'best hotels in paros' },
  { title: 'Best Restaurants in Paros', url: 'https://greektriplanner.me/blog/best-restaurants-in-paros', keywords: 'best restaurants in paros' },
  { title: 'Things to Do in Rhodes', url: 'https://greektriplanner.me/blog/things-to-do-in-rhodes', keywords: 'things to do in rhodes' },
  { title: 'Rhodes Tours', url: 'https://greektriplanner.me/blog/rhodes-tours', keywords: 'rhodes tours' },
  { title: 'Where to Stay in Rhodes', url: 'https://greektriplanner.me/blog/where-to-stay-in-rhodes', keywords: 'where to stay in rhodes' },
  { title: 'Best Hotels in Rhodes', url: 'https://greektriplanner.me/blog/best-hotels-in-rhodes', keywords: 'best hotels in rhodes' },
  { title: 'Best Restaurants in Rhodes', url: 'https://greektriplanner.me/blog/best-restaurants-in-rhodes', keywords: 'best restaurants in rhodes' },
  { title: 'Things to Do in Santorini', url: 'https://greektriplanner.me/blog/things-to-do-in-santorini', keywords: 'things to do in santorini' },
  { title: 'Santorini Tours', url: 'https://greektriplanner.me/blog/santorini-tours', keywords: 'santorini tours' },
  { title: 'Where to Stay in Santorini', url: 'https://greektriplanner.me/blog/where-to-stay-in-santorini', keywords: 'where to stay in santorini' },
  { title: 'Best Hotels in Santorini', url: 'https://greektriplanner.me/blog/best-hotels-in-santorini', keywords: 'best hotels in santorini' },
  { title: 'Best Restaurants in Santorini', url: 'https://greektriplanner.me/blog/best-restaurants-in-santorini', keywords: 'best restaurants in santorini' },
  { title: 'Things to Do in Zakynthos', url: 'https://greektriplanner.me/blog/things-to-do-in-zakynthos', keywords: 'things to do in zakynthos' },
  { title: 'Zakynthos Tours', url: 'https://greektriplanner.me/blog/zakynthos-tours', keywords: 'zakynthos tours' },
  { title: 'Best Hotels in Zakynthos', url: 'https://greektriplanner.me/blog/best-hotels-in-zakynthos', keywords: 'best hotels in zakynthos' },
  { title: 'Best Restaurants in Zakynthos', url: 'https://greektriplanner.me/blog/best-restaurants-in-zakynthos', keywords: 'best restaurants in zakynthos' },
  { title: 'Things to Do in Aegina', url: 'https://greektriplanner.me/blog/things-to-do-in-aegina', keywords: 'things to do in aegina' },
  { title: 'Best Hotels in Aegina', url: 'https://greektriplanner.me/blog/best-hotels-in-aegina', keywords: 'best hotels in aegina' },
  { title: 'Things to Do in Agios Nikolaos', url: 'https://greektriplanner.me/blog/things-to-do-in-agios-nikolaos', keywords: 'things to do in agios nikolaos' },
  { title: 'Best Hotels in Agios Nikolaos', url: 'https://greektriplanner.me/blog/best-hotels-in-agios-nikolaos', keywords: 'best hotels in agios nikolaos' },
  { title: 'Things to Do in Amorgos', url: 'https://greektriplanner.me/blog/things-to-do-in-amorgos', keywords: 'things to do in amorgos' },
  { title: 'Best Hotels in Amorgos', url: 'https://greektriplanner.me/blog/best-hotels-in-amorgos', keywords: 'best hotels in amorgos' },
  { title: 'Things to Do in Andros', url: 'https://greektriplanner.me/blog/things-to-do-in-andros', keywords: 'things to do in andros' },
  { title: 'Best Hotels in Andros', url: 'https://greektriplanner.me/blog/best-hotels-in-andros', keywords: 'best hotels in andros' },
  { title: 'Things to Do in Elounda', url: 'https://greektriplanner.me/blog/things-to-do-in-elounda', keywords: 'things to do in elounda' },
  { title: 'Best Hotels in Elounda', url: 'https://greektriplanner.me/blog/best-hotels-in-elounda', keywords: 'best hotels in elounda' },
  { title: 'Things to Do in Folegandros', url: 'https://greektriplanner.me/blog/things-to-do-in-folegandros', keywords: 'things to do in folegandros' },
  { title: 'Best Hotels in Folegandros', url: 'https://greektriplanner.me/blog/best-hotels-in-folegandros', keywords: 'best hotels in folegandros' },
  { title: 'Things to Do in Halkidiki', url: 'https://greektriplanner.me/blog/things-to-do-in-halkidiki', keywords: 'things to do in halkidiki' },
  { title: 'Best Hotels in Halkidiki', url: 'https://greektriplanner.me/blog/best-hotels-in-halkidiki', keywords: 'best hotels in halkidiki' },
  { title: 'Best Restaurants in Halkidiki', url: 'https://greektriplanner.me/blog/best-restaurants-in-halkidiki', keywords: 'best restaurants in halkidiki' },
  { title: 'Things to Do in Hydra', url: 'https://greektriplanner.me/blog/things-to-do-in-hydra', keywords: 'things to do in hydra' },
  { title: 'Best Hotels in Hydra', url: 'https://greektriplanner.me/blog/best-hotels-in-hydra', keywords: 'best hotels in hydra' },
  { title: 'Things to Do in Ikaria', url: 'https://greektriplanner.me/blog/things-to-do-in-ikaria', keywords: 'things to do in ikaria' },
  { title: 'Best Hotels in Ikaria', url: 'https://greektriplanner.me/blog/best-hotels-in-ikaria', keywords: 'best hotels in ikaria' },
  { title: 'Things to Do in Ios', url: 'https://greektriplanner.me/blog/things-to-do-in-ios', keywords: 'things to do in ios' },
  { title: 'Best Hotels in Ios', url: 'https://greektriplanner.me/blog/best-hotels-in-ios', keywords: 'best hotels in ios' },
  { title: 'Best Restaurants in Ios', url: 'https://greektriplanner.me/blog/best-restaurants-in-ios', keywords: 'best restaurants in ios' },
  { title: 'Things to Do in Kalamata', url: 'https://greektriplanner.me/blog/things-to-do-in-kalamata', keywords: 'things to do in kalamata' },
  { title: 'Best Hotels in Kalamata', url: 'https://greektriplanner.me/blog/best-hotels-in-kalamata', keywords: 'best hotels in kalamata' },
  { title: 'Things to Do in Karpathos', url: 'https://greektriplanner.me/blog/things-to-do-in-karpathos', keywords: 'things to do in karpathos' },
  { title: 'Best Hotels in Karpathos', url: 'https://greektriplanner.me/blog/best-hotels-in-karpathos', keywords: 'best hotels in karpathos' },
  { title: 'Things to Do in Kefalonia', url: 'https://greektriplanner.me/blog/things-to-do-in-kefalonia', keywords: 'things to do in kefalonia' },
  { title: 'Best Hotels in Kefalonia', url: 'https://greektriplanner.me/blog/best-hotels-in-kefalonia', keywords: 'best hotels in kefalonia' },
  { title: 'Best Restaurants in Kefalonia', url: 'https://greektriplanner.me/blog/best-restaurants-in-kefalonia', keywords: 'best restaurants in kefalonia' },
  { title: 'Things to Do in Kos', url: 'https://greektriplanner.me/blog/things-to-do-in-kos', keywords: 'things to do in kos' },
  { title: 'Best Hotels in Kos', url: 'https://greektriplanner.me/blog/best-hotels-in-kos', keywords: 'best hotels in kos' },
  { title: 'Best Restaurants in Kos', url: 'https://greektriplanner.me/blog/best-restaurants-in-kos', keywords: 'best restaurants in kos' },
  { title: 'Things to Do in Lefkada', url: 'https://greektriplanner.me/blog/things-to-do-in-lefkada', keywords: 'things to do in lefkada' },
  { title: 'Best Hotels in Lefkada', url: 'https://greektriplanner.me/blog/best-hotels-in-lefkada', keywords: 'best hotels in lefkada' },
  { title: 'Best Restaurants in Lefkada', url: 'https://greektriplanner.me/blog/best-restaurants-in-lefkada', keywords: 'best restaurants in lefkada' },
  { title: 'Things to Do in Lesbos', url: 'https://greektriplanner.me/blog/things-to-do-in-lesbos', keywords: 'things to do in lesbos' },
  { title: 'Best Hotels in Lesbos', url: 'https://greektriplanner.me/blog/best-hotels-in-lesbos', keywords: 'best hotels in lesbos' },
  { title: 'Things to Do in Monemvasia', url: 'https://greektriplanner.me/blog/things-to-do-in-monemvasia', keywords: 'things to do in monemvasia' },
  { title: 'Best Hotels in Monemvasia', url: 'https://greektriplanner.me/blog/best-hotels-in-monemvasia', keywords: 'best hotels in monemvasia' },
  { title: 'Things to Do in Nafplio', url: 'https://greektriplanner.me/blog/things-to-do-in-nafplio', keywords: 'things to do in nafplio' },
  { title: 'Best Hotels in Nafplio', url: 'https://greektriplanner.me/blog/best-hotels-in-nafplio', keywords: 'best hotels in nafplio' },
  { title: 'Best Restaurants in Nafplio', url: 'https://greektriplanner.me/blog/best-restaurants-in-nafplio', keywords: 'best restaurants in nafplio' },
  { title: 'Things to Do in Parga', url: 'https://greektriplanner.me/blog/things-to-do-in-parga', keywords: 'things to do in parga' },
  { title: 'Best Hotels in Parga', url: 'https://greektriplanner.me/blog/best-hotels-in-parga', keywords: 'best hotels in parga' },
  { title: 'Things to Do in Patmos', url: 'https://greektriplanner.me/blog/things-to-do-in-patmos', keywords: 'things to do in patmos' },
  { title: 'Best Hotels in Patmos', url: 'https://greektriplanner.me/blog/best-hotels-in-patmos', keywords: 'best hotels in patmos' },
  { title: 'Things to Do in Paxos', url: 'https://greektriplanner.me/blog/things-to-do-in-paxos', keywords: 'things to do in paxos' },
  { title: 'Best Hotels in Paxos', url: 'https://greektriplanner.me/blog/best-hotels-in-paxos', keywords: 'best hotels in paxos' },
  { title: 'Things to Do in Pelion', url: 'https://greektriplanner.me/blog/things-to-do-in-pelion', keywords: 'things to do in pelion' },
  { title: 'Best Hotels in Pelion', url: 'https://greektriplanner.me/blog/best-hotels-in-pelion', keywords: 'best hotels in pelion' },
  { title: 'Things to Do in Rethymno', url: 'https://greektriplanner.me/blog/things-to-do-in-rethymno', keywords: 'things to do in rethymno' },
  { title: 'Best Hotels in Rethymno', url: 'https://greektriplanner.me/blog/best-hotels-in-rethymno', keywords: 'best hotels in rethymno' },
  { title: 'Best Restaurants in Rethymno', url: 'https://greektriplanner.me/blog/best-restaurants-in-rethymno', keywords: 'best restaurants in rethymno' },
  { title: 'Things to Do in Samos', url: 'https://greektriplanner.me/blog/things-to-do-in-samos', keywords: 'things to do in samos' },
  { title: 'Best Hotels in Samos', url: 'https://greektriplanner.me/blog/best-hotels-in-samos', keywords: 'best hotels in samos' },
  { title: 'Things to Do in Serifos', url: 'https://greektriplanner.me/blog/things-to-do-in-serifos', keywords: 'things to do in serifos' },
  { title: 'Best Hotels in Serifos', url: 'https://greektriplanner.me/blog/best-hotels-in-serifos', keywords: 'best hotels in serifos' },
  { title: 'Things to Do in Sifnos', url: 'https://greektriplanner.me/blog/things-to-do-in-sifnos', keywords: 'things to do in sifnos' },
  { title: 'Best Hotels in Sifnos', url: 'https://greektriplanner.me/blog/best-hotels-in-sifnos', keywords: 'best hotels in sifnos' },
  { title: 'Best Restaurants in Sifnos', url: 'https://greektriplanner.me/blog/best-restaurants-in-sifnos', keywords: 'best restaurants in sifnos' },
  { title: 'Things to Do in Skiathos', url: 'https://greektriplanner.me/blog/things-to-do-in-skiathos', keywords: 'things to do in skiathos' },
  { title: 'Best Hotels in Skiathos', url: 'https://greektriplanner.me/blog/best-hotels-in-skiathos', keywords: 'best hotels in skiathos' },
  { title: 'Best Restaurants in Skiathos', url: 'https://greektriplanner.me/blog/best-restaurants-in-skiathos', keywords: 'best restaurants in skiathos' },
  { title: 'Things to Do in Skopelos', url: 'https://greektriplanner.me/blog/things-to-do-in-skopelos', keywords: 'things to do in skopelos' },
  { title: 'Best Hotels in Skopelos', url: 'https://greektriplanner.me/blog/best-hotels-in-skopelos', keywords: 'best hotels in skopelos' },
  { title: 'Things to Do in Spetses', url: 'https://greektriplanner.me/blog/things-to-do-in-spetses', keywords: 'things to do in spetses' },
  { title: 'Best Hotels in Spetses', url: 'https://greektriplanner.me/blog/best-hotels-in-spetses', keywords: 'best hotels in spetses' },
  { title: 'Things to Do in Symi', url: 'https://greektriplanner.me/blog/things-to-do-in-symi', keywords: 'things to do in symi' },
  { title: 'Best Hotels in Symi', url: 'https://greektriplanner.me/blog/best-hotels-in-symi', keywords: 'best hotels in symi' },
  { title: 'Things to Do in Syros', url: 'https://greektriplanner.me/blog/things-to-do-in-syros', keywords: 'things to do in syros' },
  { title: 'Best Hotels in Syros', url: 'https://greektriplanner.me/blog/best-hotels-in-syros', keywords: 'best hotels in syros' },
  { title: 'Best Restaurants in Syros', url: 'https://greektriplanner.me/blog/best-restaurants-in-syros', keywords: 'best restaurants in syros' },
  { title: 'Things to Do in Thasos', url: 'https://greektriplanner.me/blog/things-to-do-in-thasos', keywords: 'things to do in thasos' },
  { title: 'Best Hotels in Thasos', url: 'https://greektriplanner.me/blog/best-hotels-in-thasos', keywords: 'best hotels in thasos' },
  { title: 'Things to Do in Thessaloniki', url: 'https://greektriplanner.me/blog/things-to-do-in-thessaloniki', keywords: 'things to do in thessaloniki' },
  { title: 'Where to Stay in Thessaloniki', url: 'https://greektriplanner.me/blog/where-to-stay-in-thessaloniki', keywords: 'where to stay in thessaloniki' },
  { title: 'Best Hotels in Thessaloniki', url: 'https://greektriplanner.me/blog/best-hotels-in-thessaloniki', keywords: 'best hotels in thessaloniki' },
  { title: 'Best Restaurants in Thessaloniki', url: 'https://greektriplanner.me/blog/best-restaurants-in-thessaloniki', keywords: 'best restaurants in thessaloniki' },
  { title: 'Things to Do in Tinos', url: 'https://greektriplanner.me/blog/things-to-do-in-tinos', keywords: 'things to do in tinos' },
  { title: 'Best Hotels in Tinos', url: 'https://greektriplanner.me/blog/best-hotels-in-tinos', keywords: 'best hotels in tinos' },
  { title: 'Best Restaurants in Tinos', url: 'https://greektriplanner.me/blog/best-restaurants-in-tinos', keywords: 'best restaurants in tinos' },
  { title: 'best-cities-to-visit-in-greece', url: 'https://greektriplanner.me/blog/best-cities-to-visit-in-greece', keywords: 'best-cities-to-visit-in-greece' },
  { title: 'is-greece-expensive', url: 'https://greektriplanner.me/blog/is-greece-expensive', keywords: 'is-greece-expensive' },
  { title: 'greece-and-croatia-cruise', url: 'https://greektriplanner.me/blog/greece-and-croatia-cruise', keywords: 'greece-and-croatia-cruise' },
  { title: 'greece-and-turkey-cruise', url: 'https://greektriplanner.me/blog/greece-and-turkey-cruise', keywords: 'greece-and-turkey-cruise' },
  { title: 'santorini-vs-amalfi-coast', url: 'https://greektriplanner.me/blog/santorini-vs-amalfi-coast', keywords: 'santorini-vs-amalfi-coast' },
  { title: 'direct-flights-to-greece', url: 'https://greektriplanner.me/blog/direct-flights-to-greece', keywords: 'direct-flights-to-greece' },
  { title: 'cheap-flights-to-greece', url: 'https://greektriplanner.me/blog/cheap-flights-to-greece', keywords: 'cheap-flights-to-greece' },
  { title: 'athens-weather-by-month', url: 'https://greektriplanner.me/blog/athens-weather-by-month', keywords: 'athens-weather-by-month' },
  { title: 'cyclades-vs-ionian-islands', url: 'https://greektriplanner.me/blog/cyclades-vs-ionian-islands', keywords: 'cyclades-vs-ionian-islands' },
  { title: 'ibiza-vs-mykonos', url: 'https://greektriplanner.me/blog/ibiza-vs-mykonos', keywords: 'ibiza-vs-mykonos' },
  { title: 'car-rental-athens', url: 'https://greektriplanner.me/blog/car-rental-athens', keywords: 'car-rental-athens' },
  { title: 'car-rental-crete', url: 'https://greektriplanner.me/blog/car-rental-crete', keywords: 'car-rental-crete' },
  { title: 'car-rental-rhodes', url: 'https://greektriplanner.me/blog/car-rental-rhodes', keywords: 'car-rental-rhodes' },
  { title: 'car-rental-santorini', url: 'https://greektriplanner.me/blog/car-rental-santorini', keywords: 'car-rental-santorini' },
  { title: 'car-rental-paros', url: 'https://greektriplanner.me/blog/car-rental-paros', keywords: 'car-rental-paros' },
  { title: 'car-rental-heraklion', url: 'https://greektriplanner.me/blog/car-rental-heraklion', keywords: 'car-rental-heraklion' },
  { title: 'car-rental-chania', url: 'https://greektriplanner.me/blog/car-rental-chania', keywords: 'car-rental-chania' },
  { title: 'car-rental-mykonos', url: 'https://greektriplanner.me/blog/car-rental-mykonos', keywords: 'car-rental-mykonos' },
  { title: 'visiting-greece-in-october', url: 'https://greektriplanner.me/blog/visiting-greece-in-october', keywords: 'visiting-greece-in-october' },
  { title: 'greece-cruise-ports', url: 'https://greektriplanner.me/blog/greece-cruise-ports', keywords: 'greece-cruise-ports' },
  { title: 'crete-weather-by-month', url: 'https://greektriplanner.me/blog/crete-weather-by-month', keywords: 'crete-weather-by-month' },
  { title: 'santorini-weather-by-month', url: 'https://greektriplanner.me/blog/santorini-weather-by-month', keywords: 'santorini-weather-by-month' },
  { title: 'greece-ferry-guide', url: 'https://greektriplanner.me/blog/greece-ferry-guide', keywords: 'greece-ferry-guide' },
  { title: 'Greece Honeymoon Guide', url: 'https://greektriplanner.me/blog/greece-honeymoon-guide', keywords: 'greece honeymoon guide' },
  { title: 'Best Beaches In Santorini', url: 'https://greektriplanner.me/blog/best-beaches-in-santorini', keywords: 'best beaches in santorini' },
  { title: 'Best Beaches In Crete', url: 'https://greektriplanner.me/blog/best-beaches-in-crete', keywords: 'best beaches in crete' },
  { title: 'Athens To Santorini', url: 'https://greektriplanner.me/blog/athens-to-santorini', keywords: 'athens to santorini' },
  { title: 'Peloponnese Travel Guide', url: 'https://greektriplanner.me/blog/peloponnese-travel-guide', keywords: 'peloponnese travel guide' },
  { title: 'Best Beaches In Mykonos', url: 'https://greektriplanner.me/blog/best-beaches-in-mykonos', keywords: 'best beaches in mykonos' },
  { title: 'Best Beaches In Rhodes', url: 'https://greektriplanner.me/blog/best-beaches-in-rhodes', keywords: 'best beaches in rhodes' },
  { title: 'Greece Packing List', url: 'https://greektriplanner.me/blog/greece-packing-list', keywords: 'greece packing list' },
  { title: 'Greece Itinerary 2 Weeks', url: 'https://greektriplanner.me/blog/greece-itinerary-2-weeks', keywords: 'greece itinerary 2 weeks' },
  { title: 'Athens Airport Guide', url: 'https://greektriplanner.me/blog/athens-airport-guide', keywords: 'athens airport guide' },
  { title: 'Visiting Greece In September', url: 'https://greektriplanner.me/blog/visiting-greece-in-september', keywords: 'visiting greece in september' },
  { title: 'Visiting Greece In April May', url: 'https://greektriplanner.me/blog/visiting-greece-in-april-may', keywords: 'visiting greece in april may' },
  { title: 'Best Time To Visit Mykonos', url: 'https://greektriplanner.me/blog/best-time-to-visit-mykonos', keywords: 'best time to visit mykonos' },
  { title: 'Northern Greece Travel Guide', url: 'https://greektriplanner.me/blog/northern-greece-travel-guide', keywords: 'northern greece travel guide' },
  { title: 'Best Beaches Near Athens', url: 'https://greektriplanner.me/blog/best-beaches-near-athens', keywords: 'best beaches near athens' },
  { title: 'Best Day Trips From Thessaloniki', url: 'https://greektriplanner.me/blog/best-day-trips-from-thessaloniki', keywords: 'best day trips from thessaloniki' },
  { title: 'Greek Food Guide', url: 'https://greektriplanner.me/blog/greek-food-guide', keywords: 'greek food guide' },
  { title: 'Parthenon Acropolis Guide', url: 'https://greektriplanner.me/blog/parthenon-acropolis-guide', keywords: 'parthenon acropolis guide' },
  { title: 'Ancient Greece Guide', url: 'https://greektriplanner.me/blog/ancient-greece-guide', keywords: 'ancient greece guide' },
  { title: 'Things To Do In Greece', url: 'https://greektriplanner.me/blog/things-to-do-in-greece', keywords: 'things to do in greece' },
  { title: 'Greece Vs Italy', url: 'https://greektriplanner.me/blog/greece-vs-italy', keywords: 'greece vs italy' },
  { title: 'Best Day Trips From Athens', url: 'https://greektriplanner.me/blog/best-day-trips-from-athens', keywords: 'best day trips from athens' },
]

// Find the most relevant internal links for a given article
// Returns up to maxLinks matches based on keyword overlap with article text
export function findRelevantLinks(
  articleText: string,
  maxLinks: number = 8
): InternalLink[] {
  const text = articleText.toLowerCase()
  const scored: Array<{ link: InternalLink; score: number }> = []

  for (const link of INTERNAL_LINKS) {
    const terms = link.keywords.split(' ').filter(t => t.length > 3)
    let score = 0

    // Score by how many keyword terms appear in the article
    for (const term of terms) {
      if (text.includes(term)) score++
    }

    // Bonus: exact keyword phrase match
    if (text.includes(link.keywords)) score += 3

    if (score > 0) scored.push({ link, score })
  }

  // Sort by score descending, return top matches
  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, maxLinks)
    .map(s => s.link)
}

// Format links as a compact string for Claude's prompt
export function formatLinksForPrompt(links: InternalLink[]): string {
  return links
    .map(l => `- "${l.title}" → ${l.url}`)
    .join('\n')
}